---
version: '3.8'

networks:
  proxy_network:
    name: proxy_network
    external: true
services:
  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.portainer-secure.entrypoints=${DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.portainer-secure.rule=Host(`${PORTAINER_DOMAIN}`)'
        - 'traefik.http.routers.portainer-secure.tls=${ENABLE_SSL}'
        - 'traefik.http.routers.portainer-secure.tls.certresolver=letsencryptresolver'
        - 'traefik.http.routers.portainer-secure.service=portainer'
        - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
        - 'traefik.docker.network=proxy_network'
    container_name: portainer
    domainname: portainer
    restart: unless-stopped
    networks:
      - proxy_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${DATA_PATH}/volumes/portainer:/data
